apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-service.yaml
  - grafana-httproute.yaml
  - helmrepo.yaml
  - prometheus-helmrelease.yaml
  - prometheus-httproute.yaml
  - prometheus-namespace.yaml
  - loki-helmrelease.yaml
  - loki-httproute.yaml
  - dashboards/raspberrypi-dashboard.yaml
  - dashboards/postgresql-dashboard.yaml
