---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway-api-crds-source.yaml
  - gateway-api-crds.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - ingressclass.yaml
  - certificate.yaml
