---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-reflector-manifests
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-manifests
    namespace: flux-system
  path: ./manifests/install/crd
  prune: true
  wait: false
